<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
		<UseWindowsForms>true</UseWindowsForms>
		<Version>1.0.0</Version>
		<Authors>yyigityavuz</Authors>
		<Product>Mouse Trail</Product>
		<Copyright>Copyright (c) 2026 yyigityavuz</Copyright>
		<ApplicationManifest>app.manifest</ApplicationManifest>
	</PropertyGroup>
</Project>